### ISSUE TITLE
Stop the scrolling instantly

### ISSUE THREAD

**Issue by bricewge** [zk-phi/sublimity#13]
Is it possible to implement a way to stop the scrolling inertia without delay?
I would like to have the same behavior as nautilus in gnome for example. For example with the ```xev``` command on my touchpad when I scroll quickly and release my fingers events keept logging until the "end of the inertia", but when the inertia is going I can stop it directly (without any latency, unlike in sublimity) when i touch the touchpad again 
I'm not sure if it's well explain enough.

**Comment by zk-phi** [comment]
i've tried but it seems hard to avoid performance problems.

**Comment by bricewge** [comment]
Too bad.
