### ISSUE TITLE
sublimity-auto-hscroll-mode not working

### ISSUE THREAD

**Issue by kovan** [zk-phi/sublimity#14]
It doesn't work by default (I'm using the package.el package). 

Besides that, setting it in init.el doesn't work either, but setting it afterwards does work.

**Comment by zk-phi** [comment]
(just a reminder)

**Comment by bertschneider** [comment]
In sublimity version `1.1.3` and emacs `GNU Emacs 24.4.1 (x86_64-w64-mingw32) of 2014-10-21 on KAEL` the horizontal scrolling doesn't work out of the box for me neither. 
Enabling `sublimity-auto-hscroll-mode` (like you mentioned) does the trick.

**Comment by zk-phi** [comment]
> Enabling sublimity-auto-hscroll-mode (like you mentioned) does the trick.
you mean that `sublimity-auto-hscroll-mode` is not enabled by default right ?

**Comment by zk-phi** [comment]
closing.
