### ISSUE TITLE
sublimity-attractive & helm

### ISSUE THREAD

**Issue by mclearc** [zk-phi/sublimity#27]
This is a nice plugin but is there a way to keep sublimity from working on the helm buffer when it opens?

**Comment by zk-phi** [comment]
set `sublimity-attractive-centering-width` locally `nil` in the helm buffer.

**Comment by zk-phi** [comment]
I don't use helm so I'm not sure but it
should have something like `helm-mode-hook` thus you can hook a function like:

````
(add-hook 'helm-mode-hook
  (lambda ()
    (setq-local sublimity-attractive-centering-width nil)))
````

**Comment by mclearc** [comment]
Looks like that worked. Thanks! 👍
