### ISSUE TITLE
Text terminal support a la vim-minimap

### ISSUE THREAD

**Issue by josuah** [zk-phi/sublimity#31]
[Vim-minimap](https://github.com/severin-lemaignan/vim-minimap) has a terminal support using the python-implemented [drawille library](https://github.com/asciimoo/drawille).

![](https://cloud.githubusercontent.com/assets/7250745/8083436/d4aaf9d4-0f84-11e5-9383-cb02bba384bc.png)

It could be done as well for emacs using the elisp [implementation](https://github.com/sshbio/drawille)?

**Comment by zk-phi** [comment]
it's not impossible I think.
