### ISSUE TITLE
Sublimity not working with Spacemacs

### ISSUE THREAD

**Issue by abhi18av** [zk-phi/sublimity#34]
Hi, @zk-phi  I am literally in awe of this package for emacs but when I installed it in Spacemacs, and setting it on at startup inside user-config, I don't see anything at all. 

Please let me know if I'm missing a crucial piece or perhaps it's a bug?

**Comment by zk-phi** [comment]
Hi, @abhi18av 

> I don't see anything at all

I want you to explain more in detail. You started up `sublimity` but nothing's changed ? Or  `sublimity` broke your Emacs and it gets displaying nothing ?

**Comment by abhi18av** [comment]
And thanks @zk-phi  for the prompt reply, appreciate it.
