### ISSUE TITLE
Smooth scrolling doesn't work if line partially off screen

### ISSUE THREAD

**Issue by countvajhula** [zk-phi/sublimity#37]
I'm using Mitsuharu Yamamoto's Emacs for Mac, which supports pixel-level (as opposed to line-by-line) scrolling. I've noticed that when the page is resting on a non-line boundary (i.e. a line is only partially visible with part of it off screen), moving the cursor onto that last (or first) line causes the page to skip the way it does by default without sublimity. If on the other hand the cursor is on a line that is fully on screen, sublimity smooth scrolling kicks in and it doesn't skip.

It ought to smooth-scroll in either case.

**Comment by zk-phi** [comment]
thanks for reporting :)

do you mean this behavior ?

![screencast](https://cloud.githubusercontent.com/assets/3530521/24843038/b7151d0e-1dd9-11e7-9871-30520cf7bb61.gif)

**Comment by countvajhula** [comment]
@zk-phi Thanks for the fast response. I can't really tell in that animation, but you could do it this way:

1. Open a long file with say >100 lines
2. smooth scroll the first page so that the bottom line is partially on screen (i.e. there should still be many pages to go after this one)
3. move the cursor to the bottom line using C-n
4. The screen jumps instead of smooth scrolling

Let me know if that works, thanks!

**Comment by zk-phi** [comment]
Thanks, I'll inspect later :)

**Comment by obar** [comment]
I filed a similar bug at #55. I think this is a sub-issue, as a user should be able to specify a `scroll-margin` (or similar, `sublimity-scroll-margin` perhaps) so when the point is near the window boundary there can be a scroll action.

I don't have a fix for the general case of a scroll margin, but I did submit a pull request that solves the partial line scroll issue described here.
