### ISSUE TITLE
minimap font size is too large

### ISSUE THREAD

**Issue by mstorus** [zk-phi/sublimity#38]
I installed sublimity and enabled sublimity-mode, but the font size of the minimap is too large.
See the right side of this screenshot:

![mstorus-mbp133 root switchboard-legacy_ _sublimity ssh ssh_wrapper sh mstorus-onebox dev lyft net 104x24](https://cloud.githubusercontent.com/assets/1182738/25499464/6a938ad2-2b40-11e7-9e53-7ca01c4064b5.jpg)

Is it possible to use the minimap in terminal emacs? If so, how can I make the text smaller?

I tried modifying the `Sublimity Map Text Scale` to `-12` but it had no effect.

```
# emacs --version
GNU Emacs 24.3.1
```

**Comment by zk-phi** [comment]
@mstorus 
Emacs needs graphic display to render minimap :(

**Comment by mstorus** [comment]
There's an idea here that might be interesting for future consideration:
https://github.com/dengste/minimap/issues/12#issuecomment-166742326

**Comment by zk-phi** [comment]
i'm not sure that it's really useful, and is a low-priority feature for me (contributions are welcome anyway).
