### ISSUE TITLE
Question: Is it possible to have no overlays in the minimap?

### ISSUE THREAD

**Issue by d1egoaz** [zk-phi/sublimity#41]
I'd like to have the minimap to show no colors/overlays, I just want a minimap view of the buffer.
Is it possible to make the minimap use, let say, the fundamental-mode?

**Comment by zk-phi** [comment]
You may put another overlay on the minimap buffer to overwrite all faces with the `'default` face.

```
(add-hook 'sublimity-map-setup-hook
          (lambda ()
            (let ((ov (make-overlay (point-min) (point-max) nil nil t)))
              (overlay-put ov 'priority 100)
              (overlay-put ov 'face 'default))))
```
