### ISSUE TITLE
Slow copy/paste from OSX native clipboard

### ISSUE THREAD

**Issue by joegle** [zk-phi/sublimity#43]
I was debugging intermittent slowness on native copy/pastes on my MacBook and discovered that the slowness is proportional to the current line position of a file when sublimity is activated.  Pasting text from the native clipboard will visibly paste one character at a time when you're at the bottom of a large file. Yanking is unaffected. 

Here is the sublimity config I used ([my full emacs config](https://github.com/joegle/dot-emacs/blob/1dbe1e164740ce96cd1e7c9b6e78219bf9471aa3/init.el)):
```elisp
(require 'sublimity)
(require 'sublimity-scroll)
(sublimity-mode nil)
```

I thought this config would make sublimity totally deactivated but removing the `sublimity-scroll` require line makes native copy/pastes responsive again.

- `osx-clipboard` package didn't help
- Slowness is worst on org-mode files
- Seen on python files and elisp files

**Comment by zk-phi** [comment]
`sublimity` watches if the buffer is scrolled or not in `post-command-hook`, which is always invoked after running an arbitrary command.
OSX native clipboard maybe sends the copied text to Emacs one-character by one, and `post-command-hook` runs for each character you paste I suppose.

That case, pushing `self-insert-command` to `sublimity-ignored-scroll-commands` workarounds th e problem :
```
(push 'self-insert-command sublimity-ignored-scroll-commands)
```

**Comment by joegle** [comment]
Thank you. This workaround worked for me when I updated my MELPA sublimity package to version 20170820.827. I think I was using the MELPA stable release which didn't define `sublimity-ignored-scroll-commands`.
