### ISSUE TITLE
Minimap changes formatting of modeline

### ISSUE THREAD

**Issue by detly** [zk-phi/sublimity#46]
If I enable the minimap, bits of modeline formatting are obscured or changed for the width of the minimap. See screenshot below, and note how the modeline on the right is darker and missing its border. This happens even if I apply those changes after the package is loaded. Below is a snippet of code (that requires `use-package` to be installed) that should be a minimal example of what I'm seeing:

```elisp
(progn
  (package-initialize)

  (require 'use-package)

  (use-package base16-theme
    :config (load-theme 'base16-default-dark t)
  )

  (use-package sublimity
    :ensure t
    :config (
      progn
        (require 'sublimity)
        (require 'sublimity-map)
        (require 'sublimity-attractive)
        (sublimity-mode 1)
        (sublimity-map-set-delay nil)
        (sublimity-attractive-hide-bars)
        (sublimity-attractive-hide-vertical-border)
        (sublimity-attractive-hide-fringes)
        (set-face-attribute 'mode-line nil
          :box nil
          :overline "dark grey"
          :underline "dark grey"
        )
    )
  )
)
```

![emacs-sbm2](https://user-images.githubusercontent.com/311239/31755257-ecff177a-b4e8-11e7-9b5f-751c4918dce1.png)

**Comment by zk-phi** [comment]
minimap renders in a separate window from the `*scratch*` buffer, thus I suppose that, `mode-line-inactive` (instead of `mode-line`) face is applied to its modeline and it makes the difference.

**Comment by detly** [comment]
Maybe you could suppress the modeline altogether for the minimap. It's not really needed for it right?

**Comment by zk-phi** [comment]
I'm not sure that this should be the default behavior, you can disable the modeline in `sublimity-map-setup-hook`.

```lisp
(add-hook 'sublimity-map-setup-hook (lambda () (setq mode-line-format nil)))
```

**Comment by detly** [comment]
No problem, thanks for the code! 👍
