### ISSUE TITLE
Open minimap only when needed

### ISSUE THREAD

**Issue by azzamsa** [zk-phi/sublimity#49]
Can we open minimap only when needed ?
e.g bind something like mini-map-show to some keybinding.

So it does not distract us when we don't need it. and call it only when we need it.

**Comment by azzamsa** [comment]
Oh no. I just understand it is by design.

The option is 
- always show map.
Then I have to set `sublimity-map-set-delay` to nil. But it will make Emacs performance worse. So the is another option:
- set a delay
With a delay set to e.g 2 second. I can scroll trough the document and see where I am. then scroll again :)

Thanks for this awesome packages.
Thanks for your contribution to community.

**Comment by zk-phi** [comment]
The function `sublimity-map-show` is an interactive command, so you may bind a key to it to show the minimap manually.

**Comment by azzamsa** [comment]
Yes. I mean I don't what the minimap shows up except when I need it. 

Do I have to set the delay to very long time ?

Something like `close` and `open` minimap only when invoked with user. :)

**Comment by InspectorMustache** [comment]
I had the same problem. Turns out that the minimap automatically popping up after a certain amount of time is controlled by `run-with-idle-timer`. So to stop that from happening you can run `(cancel-timer sublimity-map--timer)`.

**Comment by azzamsa** [comment]
> (cancel-timer sublimity-map--timer)

Thanks lot for this. I don't use minimap anymore. I just minimize the font to know my position in long file. Maybe I will use your tips if it comes to minimap again.

Thanks.
