### ISSUE TITLE
Disable sumbility mode also disable linum-mode.

### ISSUE THREAD

**Issue by jcs090218** [zk-phi/sublimity#52]
Why when I disable `sublimity-mode` the `linum-mode` also get disabled. And this only happens when cursor is in *GNU Emacs* buffer.
```
M-x sublimity-mode
```

**Comment by zk-phi** [comment]
Maybe because sublimity tries to restore window margins, when sublimity-attractive is loaded.

**Comment by zk-phi** [comment]
Sublimity actually does not disable linum-mode but just clear the window margins, thus when linum-mode display is refreshed, then line numbers will be visible again. While sublimity-mode is not toggled very frequently, this is not a priority issue, at least for me.

Please reopen if the behavior is problematic. PRs are also welcome.
