### ISSUE TITLE
auto-hscroll-mode disabled?

### ISSUE THREAD

**Issue by jcs090218** [zk-phi/sublimity#53]
I saw that this package set `auto-hscroll-mode` to nil, hence the hscroll no longer working. Is there a reason to do this?

**Comment by zk-phi** [comment]
As far as I remember, animating horizontal scroll is difficult when `auto-hscoll-mode` is turned on. Thus sublimity automatically disable the mode, and turns on `sublimity-auto-hscroll-mode` instead, to control horizontal scrolling.
Anyway `sublimity-auto-hscroll-mode` defaults to `t` when `auto-hscroll-mode` is `t`, so if horizontal scrolling is not working on your system, it can be a bug of `sublimity-auto-hscroll-mode`.
