### ISSUE TITLE
Images intermittently disappear in image-mode

### ISSUE THREAD

**Issue by obar** [zk-phi/sublimity#60]
With sublimity-scroll on, switching to a buffer with an image open in it causes the image to disappear, not all of the time but I've found it can be reliably reproduced by clicking outside the boundaries of the image but in the buffer to switch to that buffer. Some more buffer switching and sometimes the image redraws. I bisected my minor modes until this stopped to diagnose the cause.

This might be specific to some systems (I'm on Ubuntu 20.04, this might not reproduce with different graphical toolkits), and maybe doesn't happen with all sublimity features, but I think it's safe to turn off sublimity for images generally by default. I will submit a pull request doing so.

**Comment by zk-phi** [comment]
Thank you for your report and fix ! Merged.
