### ISSUE TITLE
Does this work at all?

### ISSUE THREAD

**Issue by grolongo** [zk-phi/sublimity#62]
Hello, I'm having a hard time figuring out why this package doesn't work.  
I tried it on Windows and macOS with both my usual config file and with -Q.

Here is my use-package declaration:
```elisp
(use-package sublimity
  :ensure t
  :config (sublimity-mode 1))
```

Did I miss something? Literally nothing happens, I have no minimap showing at all, even when I'm toggling `sublimity-mode` with M-x. Tried with elisp file and html.

Any help?

edit: forgot to mention I'm on Emacs 27.1, if that makes any difference.

**Comment by zk-phi** [comment]
As written in the Readme.org, you need to load each features you want to enable.

https://github.com/zk-phi/sublimity#installation

**Comment by grolongo** [comment]
Nevermind. Thank you.

**Comment by zamlz** [comment]
I'm sorry but I'm still new to emacs, I was introduced to adding packages through `use-package` but I think I'm not understanding hwo to convert the `require` statements into equivalent `use-package` statements. I don't think I'm doing this correctly as emacs complains that the package doesn't exist in MELPA.

```lisp
(use-package sublimity
  :init (sublimity-mode 1))
(use-package sublimity-scroll)
(use-package sublimity-attractive
  :config (sublimity-attractive-centering-width zamlz/default-screen-width))
```
